### ISSUE TITLE
Storefront Designer integration

### ISSUE THREAD

**Issue by stuartduff** [woothemes/deli#12]
Add a notice on Deli child theme activation that explains why some of the features of certain Storefront extensions are disabled.

**Comment by jameskoster** [comment]
I reckon we should add a clearer note on the Storefront Designer listing. We don't really want to be greeting users with a message like this once they've already purchased, downloaded and installed the extension.

I've improved the integration somewhat for 1.1.1 but the usual options are still removed (buttons/header layout).
