### ISSUE TITLE
Fix order summary quantity badge numbers styling for checkout block used with the theme.

### ISSUE THREAD

**Issue by nerrad** [woothemes/deli#58]
## Describe the bug
The order summary badges for quantities in Cart and Checkout blocks aren't legible (the text color blends in with background). Screenshot:

![screenshot-bad](https://user-images.githubusercontent.com/69914963/107654139-20a14700-6c61-11eb-85d4-51e7727a3793.png)

## To Reproduce
1. Install and activate [WooCommerce Blocks feature plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/).
2. Insert the Cart block on a page.
3. Add some items to the cart then view the page you added the Cart block to.
4. View the styling of the quantity badges for the items in the cart.

## Expected behavior
Suggest leaving the style of the badges to what the blocks provide by default.

**Comment by luislard** [comment]
Cannot replicate @nerrad . CC: @jconroy 
See:
![image](https://user-images.githubusercontent.com/17932063/116412080-9b2c3c80-a836-11eb-85ed-4237ac09ddb5.png)

Best,
Luis

**Comment by luislard** [comment]
@nerrad ,
I think you refer to the checkout component in the steps to replicate.

I will submit a PR
